runtime: go
service: api-go
instance_class: F1
env: standard

automatic_scaling:
  max_instances: 1

env_variables:
  DB_HOST: "/cloudsql/dev-sis-operativos:us-central1:devchepita"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_PASSWORD: "Chepita123789@"
  DB_NAME: "bd_sis_operativos"
  JWT_SECRET: "supersecretkey"
  PORT: "8080"