version: "3.9"

services:
  api:
    build: .
    container_name: api-go
    ports:
      - "8080"
    restart: always
    environment:
      - PORT=8080
      - DB_HOST=35.188.19.96
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=Chepita123789@
      - DB_NAME=bd_sis_operativos

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot:/etc/letsencrypt
    depends_on:
      - api
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    entrypoint: /bin/sh